In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
social = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab on ml/Social_Network_Ads.csv')
social

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [21]:
X = fitness.iloc[:,1:3].values
Y = fitness.iloc[:,-1].values
X,Y

(array([[ 19000,      0],
        [ 20000,      0],
        [ 43000,      0],
        [ 57000,      0],
        [ 76000,      0],
        [ 58000,      0],
        [ 84000,      0],
        [150000,      1],
        [ 33000,      0],
        [ 65000,      0],
        [ 80000,      0],
        [ 52000,      0],
        [ 86000,      0],
        [ 18000,      0],
        [ 82000,      0],
        [ 80000,      0],
        [ 25000,      1],
        [ 26000,      1],
        [ 28000,      1],
        [ 29000,      1],
        [ 22000,      1],
        [ 49000,      1],
        [ 41000,      1],
        [ 22000,      1],
        [ 23000,      1],
        [ 20000,      1],
        [ 28000,      1],
        [ 30000,      1],
        [ 43000,      0],
        [ 18000,      0],
        [ 74000,      0],
        [137000,      1],
        [ 16000,      0],
        [ 44000,      0],
        [ 90000,      0],
        [ 27000,      0],
        [ 28000,      0],
        [ 49000,      0],
        [ 72

In [22]:
from sklearn.model_selection import  train_test_split
X_train,X_test,Y_train ,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)
print(X_train)

[[ 39000      0]
 [120000      1]
 [ 50000      0]
 [135000      1]
 [ 21000      1]
 [104000      1]
 [ 42000      0]
 [ 61000      0]
 [ 50000      0]
 [ 63000      0]
 [ 25000      0]
 [ 50000      0]
 [ 73000      1]
 [ 49000      1]
 [ 29000      1]
 [ 65000      0]
 [131000      1]
 [ 89000      0]
 [ 82000      0]
 [ 51000      1]
 [ 15000      0]
 [102000      1]
 [112000      0]
 [107000      1]
 [ 53000      0]
 [ 59000      0]
 [ 41000      1]
 [134000      1]
 [113000      1]
 [148000      1]
 [ 15000      0]
 [ 42000      1]
 [ 19000      0]
 [149000      1]
 [ 96000      0]
 [ 59000      0]
 [ 96000      1]
 [ 89000      0]
 [ 72000      0]
 [ 26000      1]
 [ 69000      0]
 [ 82000      0]
 [ 74000      0]
 [ 80000      0]
 [ 72000      0]
 [149000      1]
 [ 71000      1]
 [146000      1]
 [ 79000      1]
 [ 75000      0]
 [ 51000      0]
 [ 75000      0]
 [ 78000      1]
 [ 61000      0]
 [108000      1]
 [ 82000      0]
 [ 74000      1]
 [ 65000      0]
 [ 80000      

In [23]:
print(Y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [24]:
print(X_test)

[[ 87000      0]
 [ 50000      0]
 [ 75000      0]
 [ 79000      0]
 [ 50000      0]
 [ 20000      0]
 [ 15000      0]
 [144000      1]
 [ 68000      0]
 [ 43000      0]
 [ 49000      0]
 [ 55000      0]
 [ 55000      0]
 [ 77000      0]
 [ 86000      0]
 [117000      0]
 [ 77000      0]
 [ 85000      0]
 [130000      1]
 [ 22000      0]
 [ 47000      0]
 [144000      1]
 [ 51000      0]
 [105000      1]
 [ 28000      0]
 [141000      1]
 [ 87000      0]
 [ 80000      0]
 [ 62000      0]
 [ 86000      0]
 [ 88000      0]
 [ 79000      1]
 [ 60000      1]
 [ 53000      0]
 [ 58000      0]
 [ 52000      0]
 [ 81000      0]
 [ 43000      0]
 [ 34000      0]
 [ 36000      1]
 [ 88000      0]
 [ 52000      0]
 [ 84000      0]
 [ 20000      0]
 [112000      1]
 [ 58000      0]
 [ 80000      0]
 [ 90000      1]
 [ 30000      0]
 [ 86000      1]
 [122000      1]
 [ 25000      0]
 [ 57000      0]
 [115000      0]
 [ 88000      1]
 [ 32000      1]
 [ 83000      0]
 [ 80000      0]
 [ 28000      

In [25]:
print(Y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.88670699 -0.76635604]
 [ 1.46173768  1.30487651]
 [-0.5677824  -0.76635604]
 [ 1.89663484  1.30487651]
 [-1.40858358  1.30487651]
 [ 0.99784738  1.30487651]
 [-0.79972756 -0.76635604]
 [-0.24885782 -0.76635604]
 [-0.5677824  -0.76635604]
 [-0.19087153 -0.76635604]
 [-1.29261101 -0.76635604]
 [-0.5677824  -0.76635604]
 [ 0.09905991  1.30487651]
 [-0.59677555  1.30487651]
 [-1.17663843  1.30487651]
 [-0.13288524 -0.76635604]
 [ 1.78066227  1.30487651]
 [ 0.56295021 -0.76635604]
 [ 0.35999821 -0.76635604]
 [-0.53878926  1.30487651]
 [-1.58254245 -0.76635604]
 [ 0.93986109  1.30487651]
 [ 1.22979253 -0.76635604]
 [ 1.08482681  1.30487651]
 [-0.48080297 -0.76635604]
 [-0.30684411 -0.76635604]
 [-0.8287207   1.30487651]
 [ 1.8676417   1.30487651]
 [ 1.25878567  1.30487651]
 [ 2.27354572  1.30487651]
 [-1.58254245 -0.76635604]
 [-0.79972756  1.30487651]
 [-1.46656987 -0.76635604]
 [ 2.30253886  1.30487651]
 [ 0.76590222 -0.76635604]
 [-0.30684411 -0.76635604]
 [ 0.76590222  1.30487651]
 

In [ ]:
print(X_test)

In [28]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [29]:
print(classifier.predict(sc.transform([[30,87000]])))

[1]


In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

In [32]:
print(classifier.predict(sc.transform([[30,87000]])))

[1]


In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))