In [127]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#**Importing libraries and dataset**

In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
fitness = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab on ml/fitness_class_2212.csv')
fitness

booking_id  months_as_member  weight days_before day_of_week time  \
0              1                17   79.56           8         Wed   PM   
1              2                10   79.01           2         Mon   AM   
2              3                16   74.53          14         Sun   AM   
3              4                 5   86.12          10         Fri   AM   
4              5                15   69.29           8         Thu   AM   
...          ...               ...     ...         ...         ...  ...   
1495        1496                21   79.51          10         Fri   AM   
1496        1497                29   89.55           2         Mon   AM   
1497        1498                 9   87.38           4         Tue   AM   
1498        1499                34   68.64          14         Sun   AM   
1499        1500                20   94.39           8         Thu   AM   

      category  attended  
0     Strength         0  
1         HIIT         0  
2     Strength         0  
3      Cycling         0  
4         HIIT         0  
...        ...       ...  
1495      HIIT         0  
1496  Strength         0  
1497      HIIT         0  
1498      Aqua         0  
1499   Cycling         1  

[1500 rows x 8 columns]

#**Using iloc function, Splitting dataset into train and test dataset**

In [129]:
from sklearn.model_selection import train_test_split
X = fitness.iloc[:,1:2].values
Y = fitness.iloc[:,-1].values
X
X_train, X_test, Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

#printing X_Train dataset
print(X_train)

[[25]
 [ 5]
 [ 9]
 ...
 [ 4]
 [ 8]
 [24]]


In [130]:
#printing Y_Train dataset
print(Y_train)

[0 0 0 ... 0 0 1]


In [131]:
#printing X_Test dataset
print(X_test)

[[  5]
 [  7]
 [ 20]
 [ 53]
 [ 32]
 [ 38]
 [  9]
 [ 32]
 [ 15]
 [  6]
 [ 11]
 [  5]
 [ 11]
 [ 34]
 [ 31]
 [ 19]
 [ 12]
 [  5]
 [  8]
 [  4]
 [  6]
 [  6]
 [  6]
 [ 11]
 [ 30]
 [ 23]
 [ 13]
 [ 21]
 [  8]
 [ 13]
 [ 10]
 [  5]
 [ 26]
 [ 32]
 [ 16]
 [  6]
 [ 18]
 [ 11]
 [ 17]
 [ 15]
 [ 38]
 [ 25]
 [  9]
 [ 22]
 [  7]
 [  6]
 [ 12]
 [  7]
 [ 12]
 [ 38]
 [  9]
 [ 11]
 [  5]
 [ 24]
 [ 22]
 [ 16]
 [  4]
 [ 14]
 [  9]
 [ 15]
 [ 21]
 [ 11]
 [ 16]
 [ 48]
 [ 31]
 [ 13]
 [  6]
 [ 18]
 [ 58]
 [  5]
 [ 33]
 [  9]
 [ 13]
 [ 18]
 [ 21]
 [ 30]
 [  9]
 [ 16]
 [ 29]
 [  4]
 [ 12]
 [ 21]
 [ 10]
 [  9]
 [ 16]
 [  3]
 [ 18]
 [ 10]
 [ 18]
 [ 20]
 [  8]
 [ 17]
 [  3]
 [  9]
 [  5]
 [ 19]
 [  6]
 [  8]
 [  8]
 [  9]
 [ 25]
 [  9]
 [  6]
 [ 12]
 [  5]
 [  6]
 [  5]
 [  6]
 [ 13]
 [  7]
 [ 53]
 [ 15]
 [ 19]
 [ 32]
 [  7]
 [ 19]
 [  3]
 [ 19]
 [ 25]
 [ 11]
 [ 12]
 [  6]
 [ 13]
 [ 10]
 [  9]
 [ 13]
 [ 21]
 [  8]
 [111]
 [ 14]
 [ 11]
 [ 23]
 [  6]
 [  4]
 [ 14]
 [ 13]
 [ 21]
 [  6]
 [ 15]
 [ 20]
 [ 14]
 [ 16]
 [ 41]

In [132]:
#printing X_Train dataset
print(Y_test)


[0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 1
 1 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0
 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1
 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0
 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0
 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0
 1 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0
 1 1 1 0 0 0]


#**Using Feature scaling to scale the values**

In [133]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [134]:
#printing X_Train dataset after feature scaling
print(X_train)

[[ 0.71164371]
 [-0.80679948]
 [-0.50311085]
 ...
 [-0.88272164]
 [-0.57903301]
 [ 0.63572155]]


In [135]:
#printing X_Test dataset after feature scaling
print(X_test)

[[-0.80679948]
 [-0.65495516]
 [ 0.33203291]
 [ 2.83746418]
 [ 1.24309883]
 [ 1.69863179]
 [-0.50311085]
 [ 1.24309883]
 [-0.04757789]
 [-0.73087732]
 [-0.35126653]
 [-0.80679948]
 [-0.35126653]
 [ 1.39494315]
 [ 1.16717667]
 [ 0.25611075]
 [-0.27534437]
 [-0.80679948]
 [-0.57903301]
 [-0.88272164]
 [-0.73087732]
 [-0.73087732]
 [-0.73087732]
 [-0.35126653]
 [ 1.09125451]
 [ 0.55979939]
 [-0.19942221]
 [ 0.40795507]
 [-0.57903301]
 [-0.19942221]
 [-0.42718869]
 [-0.80679948]
 [ 0.78756587]
 [ 1.24309883]
 [ 0.02834427]
 [-0.73087732]
 [ 0.18018859]
 [-0.35126653]
 [ 0.10426643]
 [-0.04757789]
 [ 1.69863179]
 [ 0.71164371]
 [-0.50311085]
 [ 0.48387723]
 [-0.65495516]
 [-0.73087732]
 [-0.27534437]
 [-0.65495516]
 [-0.27534437]
 [ 1.69863179]
 [-0.50311085]
 [-0.35126653]
 [-0.80679948]
 [ 0.63572155]
 [ 0.48387723]
 [ 0.02834427]
 [-0.88272164]
 [-0.12350005]
 [-0.50311085]
 [-0.04757789]
 [ 0.40795507]
 [-0.35126653]
 [ 0.02834427]
 [ 2.45785339]
 [ 1.16717667]
 [-0.19942221]
 [-0.73087

#**Training the logistic regression model on the training dataset**

In [136]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [140]:
print(classifier.predict(scaler.transform([[30]])))

[1]


In [144]:
Y_pred =classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]

In [ ]:
# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(cm)

# Precision
precision = precision_score(Y_test, Y_pred)
print("\nPrecision:", precision)

# Recall
recall = recall_score(Y_test, Y_pred)
print("Recall:", recall)

# F1 Score
f1 = f1_score(Y_test, Y_pred)
print("F1 Score:", f1)

# Accuracy
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)