In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
housePrice = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab on ml/house_price_corl.csv')
housePrice

Square Feet  Bedrooms  Bathrooms  Garage Size   House Price
0   2195.254016  5.068325   1.409423     2.719666  6.736767e+05
1   2860.757465  5.991523   2.126722     2.322142  8.565531e+05
2   2411.053504  5.557301   1.583279     0.999435  7.219910e+05
3   2179.532732  5.321254   1.269370     0.243304  6.766694e+05
4   1694.619197  3.637992   0.871988     1.221724  4.867076e+05
..          ...       ...        ...          ...           ...
95   732.765448  1.955990   0.590700     2.876948  2.274353e+05
96  2346.051739  4.919518   1.270870     1.066107  6.696193e+05
97    80.430185  0.415217   0.902407     1.070121  3.145710e+04
98  3315.760117  6.689549   2.630800     0.048986  1.012751e+06
99    18.781905  0.471980   0.970226     0.555697  7.053013e+03

[100 rows x 5 columns]

#Using iloc function on dataset

In [ ]:
X =housePrice.iloc[:,0:4].values
Y =housePrice.iloc[:,:4].values
X,Y

#Training and testing the dataset

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.model_selection  import train_test_split
X_train ,X_test, Y_train , Y_test = train_test_split(X,Y, test_size=0.3, random_state=0)
X_train ,X_test, Y_train , Y_test

(array([[6.35878335e+02, 1.96918544e+00, 5.58767947e-01, 5.61392675e-01],
        [1.27193272e+03, 2.70855959e+00, 9.28986643e-01, 2.57316793e+00],
        [1.27427581e+03, 2.94677268e+00, 1.00572251e+00, 1.88138856e-01],
        [3.35177963e+03, 7.43354982e+00, 1.73984508e+00, 2.71213318e+00],
        [1.75440605e+03, 4.37693817e+00, 1.81763497e+00, 1.06087307e-01],
        [3.77867567e+03, 7.85892615e+00, 2.10484551e+00, 2.08687634e+00],
        [3.11262700e+03, 7.10698937e+00, 2.14463062e+00, 2.58165352e+00],
        [2.61243330e+03, 6.03218556e+00, 1.85840912e+00, 8.32788293e-01],
        [5.52731805e+02, 1.97184594e+00, 1.20589522e+00, 1.37073427e+00],
        [2.95705432e+03, 6.70780634e+00, 1.71022878e+00, 7.20060820e-01],
        [2.86075747e+03, 5.99152290e+00, 2.12672222e+00, 2.32214200e+00],
        [4.41500565e+02, 1.33654381e+00, 3.21044225e-01, 2.71195187e+00],
        [2.79052478e+03, 6.01691449e+00, 1.91264150e+00, 1.37956765e+00],
        [1.74812782e+03, 3.86381750e+0

In [ ]:
from sklearn.metrics import mean_squared_error
alphas = [0.1, 1.0, 10.0]
for alpha in alphas:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train, Y_train)
    Y_pred = ridge.predict(X_test)
    mse = mean_squared_error(Y_test, Y_pred)
    print(f"Alpha = {alpha}, MSE = {mse}")
    print(f"Coefficients for Alpha = {alpha}: {ridge.coef_}")

for alpha in alphas:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train, Y_train)
    print(f"Alpha = {alpha}, Coefficients = {ridge.coef_},MSE = {mse}")

Alpha = 0.1, MSE = 2.0637306036001102e-05
Coefficients for Alpha = 0.1: [[ 9.99999923e-01  3.72034247e-05  4.45122388e-06  4.34755851e-07]
 [ 3.72034292e-05  9.80575237e-01  2.29838941e-03  1.53268658e-04]
 [ 4.45122250e-06  2.29838941e-03  9.82418979e-01 -1.33467709e-03]
 [ 4.34755750e-07  1.53268658e-04 -1.33467709e-03  9.97879843e-01]]
Alpha = 1.0, MSE = 0.001496535897068376
Coefficients for Alpha = 1.0: [[ 9.99999339e-01  3.17453119e-04  4.40575222e-05  4.17653813e-06]
 [ 3.17453120e-04  8.34956606e-01  1.68851807e-02  1.08155994e-03]
 [ 4.40575217e-05  1.68851807e-02  8.48626408e-01 -1.12897410e-02]
 [ 4.17653810e-06  1.08155994e-03 -1.12897410e-02  9.79329948e-01]]
Alpha = 10.0, MSE = 0.02768682051483691
Coefficients for Alpha = 10.0: [[ 9.99997194e-01  1.29379477e-03  2.68743751e-04  2.28094465e-05]
 [ 1.29379477e-03  3.37714257e-01  2.88201237e-02  1.21462890e-03]
 [ 2.68743752e-04  2.88201237e-02  3.62818019e-01 -4.03651419e-02]
 [ 2.28094466e-05  1.21462890e-03 -4.03651419e-0